---

- name: Aprovisionamiento de la máquina de desarrollo
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - role: geerlingguy.git
    - role: gantsign.oh-my-zsh
      users:
        - username: jeastman
