---

- name: Aprovisionamiento de la máquina de desarrollo
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - commons
    - aws-cli
    - docker
    - docker-compose
    - minikube
    - kubectl
    - role: oh-my-zsh
      users:
        - username: jeastman
