- name: docker
  src: geerlingguy.docker

- name: docker-compose
  src: andrewrothstein.docker-compose

- name: oh-my-zsh
  src: gantsign.oh-my-zsh

# docker
# docker-compose
# kubectl
# minikube
# nvm/node.js
# Opera (browser)
# podman
# rustc
# terraform
# Visual Studio Code
