- name: docker
  src: geerlingguy.docker

- name: docker-compose
  src: andrewrothstein.docker-compose

- name: minikube
  src: gantsign.minikube

- name: oh-my-zsh
  src: gantsign.oh-my-zsh

# minikube
# kubectl

# nvm/node.js
# podman
# terraform
# Visual Studio Code
