- name: docker
  src: geerlingguy.docker

- name: docker-compose
  src: andrewrothstein.docker-compose

- name: minikube
  src: gantsign.minikube

- name: kubectl
  src: andrewrothstein.kubectl

- name: oh-my-zsh
  src: gantsign.oh-my-zsh

# nvm/node.js
# podman
# terraform
# Visual Studio Code
