- name: docker
  src: geerlingguy.docker

- name: docker-compose
  src: andrewrothstein.docker-compose

- name: minikube
  src: gantsign.minikube

- name: kubectl
  src: andrewrothstein.kubectl

- name: nvm
  src: stephdewit.nvm

- name: oh-my-zsh
  src: gantsign.oh-my-zsh

- name: vsc
  src: gantsign.visual-studio-code