- name: Add dbeaver public key
  apt_key:
    url: https://dbeaver.io/debs/dbeaver.gpg.key
    state: present
    
- name: Add Debian repository and install DBeaver CE
  apt_repository:
    repo: deb https://dbeaver.io/debs/dbeaver-ce / 
    state: present

- name: Update repo
  apt:
    update_cache: yes

- name: Install DBeaver CE
  apt:
    name: dbeaver-ce
    state: present

